//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaheen.IshtiraqEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int subscriptionId { get; set; }
        public string subscriptionCode { get; set; }
        public Nullable<int> personId { get; set; }
        public Nullable<int> agentId { get; set; }
        public Nullable<decimal> pendingAmount { get; set; }
        public Nullable<System.DateTime> subscriptionDate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> subscriptionType { get; set; }
    }
}
