//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaheen.ShaheenDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int agentId { get; set; }
        public string agentName { get; set; }
        public string agentAddress { get; set; }
        public int areaId { get; set; }
        public int cityId { get; set; }
        public int districtId { get; set; }
        public int stateId { get; set; }
        public int countryId { get; set; }
        public string pin { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
    }
}
