//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaheen.ShaheenDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentId { get; set; }
        public int subscriptionId { get; set; }
        public string paymentType { get; set; }
        public System.DateTime paymentDate { get; set; }
        public Nullable<System.DateTime> moDate { get; set; }
        public string chequeNo { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public decimal amountPaid { get; set; }
        public string receiptNo { get; set; }
        public string bankName { get; set; }
    }
}
