//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaheen.ShaheenDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int subscriptionId { get; set; }
        public string subscriptionCode { get; set; }
        public int personId { get; set; }
        public int agentId { get; set; }
        public decimal pendingAmount { get; set; }
        public System.DateTime subscriptionDate { get; set; }
    }
}
