//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaheen.IshraqEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public int districtId { get; set; }
        public string districtName { get; set; }
        public int stateId { get; set; }
    }
}
